COCOS2DFILES=\
CCAction.m\
CCAtlasNode.m\
CCBlockSupport.m\
CCConfiguration.m\
CCGrid3DAction.m\
CCGridAction.m\
CCInstantAction.m \
CCPageTurnTransition.m \
CCProgressTimerActions.m\
CCPropertyAction.m\
CCScene.m\
CCTextureNode.m\
CCTiledGridAction.m\
cocos2d.m\
CCTexture2D.m \
CCActionManager.m\
CCBitmapFontAtlas.m\
CCCameraAction.m\
CCCamera.m\
CCCompatibility.m\
CCDirector.m\
CCDrawingPrimitives.m\
CCEaseAction.m\
CCGrabber.m\
CCInstantAction.m\
CCGrid.m\
CCLabelAtlas.m\
CCLabel.m\
CCLayer.m\
CCIntervalAction.m\
CCMenuItem.m\
CCMenu.m\
CCNode.m\
CCMotionStreak.m\
CCPageTurn3DAction.m\
CCParallaxNode.m\
CCParticleExamples.m\
CCParticleSystem.m\
CCPointParticleSystem.m\
CCProgressTimer.m\
CCPVRTexture.m\
CCQuadParticleSystem.m\
CCRadialTransition.m\
CCRenderTexture.m\
CCRibbon.m\
CCScheduler.m\
CCSpriteFrameCache.m\
CCSpriteFrame.m\
CCSprite.m\
CCSpriteSheet.m\
CCTexture2D.m\
CCTextureAtlas.m\
CCTextureCache.m\
CCTileMapAtlas.m\
CCTMXLayer.m\
CCTMXObjectGroup.m\
CCTMXTiledMap.m\
CCTMXXMLParser.m\
CCTouchDispatcher.m\
CCTouchHandler.m\
CCTransition.m\
#Support/CCFileUtils.m
