COCOS2DFILES=\
CCAction.m\
CCAtlasNode.m\
CCBlockSupport.m\
CCConfiguration.m\
CCGrid3DAction.m\
CCGridAction.m\
CCInstantAction.m \
CCPageTurnTransition.m \
CCProgressTimerActions.m\
CCPropertyAction.m\
CCScene.m\
CCTextureNode.m\
CCTiledGridAction.m\
cocos2d.m\
CCTexture2D.m \
CCActionManager.m\
CCBitmapFontAtlas.m\
CCCameraAction.m\
CCCamera.m\
CCCompatibility.m\
CCDirector.m\
CCDrawingPrimitives.m\
CCEaseAction.m\
CCGrabber.m\
CCInstantAction.m\
CCGrid.m\
CCLabelAtlas.m\
CCLabel.m\
CCLayer.m\
CCIntervalAction.m\
CCMenuItem.m\
CCMenu.m\
CCNode.m\
CCMotionStreak.m\
CCPageTurn3DAction.m\
CCParallaxNode.m\
CCParticleExamples.m\
CCParticleSystem.m\
CCPointParticleSystem.m\
CCProgressTimer.m\
CCPVRTexture.m\
CCQuadParticleSystem.m\
CCRadialTransition.m\
CCRenderTexture.m\
CCRibbon.m\
CCScheduler.m\
CCSpriteFrameCache.m\
CCSpriteFrame.m\
CCSprite.m\
CCSpriteSheet.m\
CCTexture2D.m\
CCTextureAtlas.m\
CCTextureCache.m\
CCTileMapAtlas.m\
CCTMXLayer.m\
CCTMXObjectGroup.m\
CCTMXTiledMap.m\
CCTMXXMLParser.m\
CCTouchDispatcher.m\
CCTouchHandler.m\
CCTransition.m\



COCOS2D_HEADERFILES=\
CCAction.h\
CCActionManager.h\
CCAtlasNode.h\
CCBitmapFontAtlas.h\
CCBlockSupport.h\
CCCameraAction.h\
CCCamera.h\
CCCompatibility.h\
ccConfig.h\
CCConfiguration.h\
CCDirector.h\
CCDrawingPrimitives.h\
CCEaseAction.h\
ccExceptions.h\
CCGrabber.h\
CCGrid3DAction.h\
CCGridAction.h\
CCGrid.h\
CCInstantAction.h\
CCIntervalAction.h\
CCLabelAtlas.h\
CCLabel.h\
CCLayer.h\
ccMacros.h\
CCMenu.h\
CCMenuItem.h\
CCMotionStreak.h\
CCNode.h\
CCPageTurn3DAction.h\
CCPageTurnTransition.h\
CCParallaxNode.h\
CCParticleExamples.h\
CCParticleSystem.h\
CCPointParticleSystem.h\
CCProgressTimerActions.h\
CCProgressTimer.h\
CCPropertyAction.h\
CCProtocols.h\
CCPVRTexture.h\
CCQuadParticleSystem.h\
CCRadialTransition.h\
CCRenderTexture.h\
CCRibbon.h\
CCScene.h\
CCScheduler.h\
CCSpriteFrameCache.h\
CCSpriteFrame.h\
CCSprite.h\
CCSpriteSheet.h\
CCTexture2D.h\
CCTextureAtlas.h\
CCTextureCache.h\
CCTextureNode.h\
CCTiledGridAction.h\
CCTileMapAtlas.h\
CCTMXLayer.h\
CCTMXObjectGroup.h\
CCTMXTiledMap.h\
CCTMXXMLParser.h\
CCTouchDelegateProtocol.h\
CCTouchDispatcher.h\
CCTouchHandler.h\
CCTransition.h\
ccTypes.h\
cocos2d.h\


