GNUSTEP_MAKEFILES = /usr/share/GNUstep/Makefiles/


include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = HelloWorld BasicSpriteTest CCNodeTest TouchesTest
include $(GNUSTEP_MAKEFILES)/aggregate.make
include localmakefile
-include GNUmakefile.postamble
