GNUSTEP_MAKEFILES = /usr/share/GNUstep/Makefiles/


include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECTS = HelloWorld BasicSpriteTest CCNodeTest
include $(GNUSTEP_MAKEFILES)/aggregate.make

-include GNUmakefile.postamble
