GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/
include $(GNUSTEP_MAKEFILES)/common.make




SUBPROJECT_NAME = Collision

Collision_CC_FILES = b2CircleContact.cpp  b2ContactSolver.cpp b2PolygonContact.cpp b2Contact.cpp        b2PolygonAndCircleContact.cpp b2TOISolver.cpp


Collision_CPPFLAGS = -I ../../../


include $(GNUSTEP_MAKEFILES)/subproject.make





