GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/
include $(GNUSTEP_MAKEFILES)/common.make




SUBPROJECT_NAME = Collision

Collision_CC_FILES = b2BlockAllocator.cpp  b2Math.cpp  b2Settings.cpp  b2StackAllocator.cpp


Collision_CPPFLAGS = -I ../../ 


include $(GNUSTEP_MAKEFILES)/subproject.make





