GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/
include $(GNUSTEP_MAKEFILES)/common.make




SUBPROJECT_NAME = Support
Support_HEADER_FILES = 
Support_HEADER_FILES_INSTALL_DIR = CoCoStep
Support_OBJC_FILES += CCFileUtils.m  CGPointExtension.m  TGAlib.m  ZipUtils.m GNUStep.m\
CCProfiling.m    TransformUtils.m EAGLView.m 


Support_C_FILES = base64.c glu.c


Support_CPPFLAGS = -I ../ 

include $(GNUSTEP_MAKEFILES)/subproject.make





