GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/

include $(GNUSTEP_MAKEFILES)/common.make


LIBRARY_NAME = libCoCoStepSupport
libCoCoStepSupport_HEADER_FILES = 
libCoCoStepSupport_HEADER_FILES_INSTALL_DIR = CoCoStepSupport
libCoCoStepSupport_OBJC_FILES += CCFileUtils.m  CGPointExtension.m  TGAlib.m  ZipUtils.m GNUStep.m\
CCProfiling.m    TransformUtils.m EAGLView.m 


libCoCoStepSupport_C_FILES = base64.c glu.c


libCoCoStepSupport_CPPFLAGS = -I ../ 

include $(GNUSTEP_MAKEFILES)/library.make


GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/


