GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/
include $(GNUSTEP_MAKEFILES)/common.make




SUBPROJECT_NAME = Collision

Collision_CC_FILES = b2BroadPhase.cpp      b2Collision.cpp   b2TimeOfImpact.cpp b2CollideCircle.cpp   b2Distance.cpp b2CollidePolygon.cpp  b2DynamicTree.cpp


Collision_CPPFLAGS = -I ../../ 
Collision_SUBPROJECTS = Shapes

include $(GNUSTEP_MAKEFILES)/subproject.make





