GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/
include $(GNUSTEP_MAKEFILES)/common.make




SUBPROJECT_NAME = Collision

Collision_CC_FILES = b2DistanceJoint.cpp  b2Joint.cpp  b2PrismaticJoint.cpp  b2WeldJoint.cpp b2FrictionJoint.cpp  b2LineJoint.cpp   b2PulleyJoint.cpp b2GearJoint.cpp      b2MouseJoint.cpp  b2RevoluteJoint.cpp


Collision_CPPFLAGS = -I ../../../


include $(GNUSTEP_MAKEFILES)/subproject.make





