GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/
include $(GNUSTEP_MAKEFILES)/common.make




SUBPROJECT_NAME = StubKit
StubKit_HEADER_FILES = UIApplication.h  UIImage.h  UITouch.h Objc2BackPort.h UIKit.h CGGeometry.h
StubKit_HEADER_FILES_INSTALL_DIR = CoCoStep/UIKit
StubKit_OBJC_FILES += UIApplication.m  UITouch.m 
#StubKit_INCLUDE_DIRS = -I ../StubKit

#Support_C_FILES = base64.c glu.c


#Support_CPPFLAGS = -I ../ 

include $(GNUSTEP_MAKEFILES)/subproject.make





