GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/
include $(GNUSTEP_MAKEFILES)/common.make


SUBPROJECT_NAME = Box2d
Box2d_SUBPROJECTS = Collision Common Dynamics

include $(GNUSTEP_MAKEFILES)/subproject.make







