#GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/
include $(GNUSTEP_MAKEFILES)/common.make




SUBPROJECT_NAME = Shapes

Shapes_CC_FILES = b2CircleShape.cpp  b2PolygonShape.cpp

Shapes_CPPFLAGS = -I ../../../


include $(GNUSTEP_MAKEFILES)/subproject.make





