GNUSTEP_MAKEFILES=/usr/share/GNUstep/Makefiles/
include $(GNUSTEP_MAKEFILES)/common.make




SUBPROJECT_NAME = Collision

Collision_CC_FILES = b2Body.cpp            b2Fixture.cpp b2WorldCallbacks.cpp b2ContactManager.cpp  b2Island.cpp   b2World.cpp

Collision_SUBPROJECTS = Contacts Joints

Collision_CPPFLAGS = -I ../../ 


include $(GNUSTEP_MAKEFILES)/subproject.make





